version: 2
jobs:
    build:
        working_directory: /go/src/github.com/jobtalk/thor
        docker:
            - image: golang:latest
              environment:
                  GO15VENDOREXPERIMENT: 1
        steps:
            - checkout
            - run:
                name: "Install glide"
                command: |
                    go get github.com/Masterminds/glide
                    go install github.com/Masterminds/glide
            - run:
                name: "Install github-release"
                command: |
                    go get github.com/aktau/github-release
                    go install github.com/aktau/github-release
            - run:
                name: "Install packages"
                command: |
                    glide i
            - run:
                name: "run test"
                command: |
                    go test $(glide novendor)
            - run:
                name: "build thor"
                command: |
                    make
            - deploy:
                name: "release head version"
                command: |
                    if [ "${CIRCLE_BRANCH}" == "make" ]; then
                        HASH=$(git rev-parse --short HEAD)
                        github-release release --user jobtalk --repo thor --name "${HASH}" --pre-release --description $(date) --tag $HASH
                    fi
